version: "3.8"
services:
  web:
    image: i4mcloud/demo-pub:1.0
    # build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/apartmentData
      - MQTT_BROKER_URL=mqtts://mqtt.cgobinak.rahtiapp.fi
      - TOPIC='vacant/allapartments'
      - MQTT_PORT=443
    restart: always

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=apartmentData

  discordpublisher:
    image: i4mcloud/demo-sub:1.0
    ports:
      - "3001:3001"
    environment:
      - MQTT_BROKER_URL=mqtts://mqtt.cgobinak.rahtiapp.fi
      - TOPIC='vacant/allapartments'
      - MQTT_PORT=443
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1316911925765869679/41nef5efwuBNChp7ymXGnCNMx_6rkWHUud-Cu73xeFg3ryTJ80SQpOYsDCL-xggsfTmM
    restart: always
